/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-14 17:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Download_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\n");
      out.write("<!--\n");
      out.write("	BIOMaaS by FreeHTML5.co\n");
      out.write("	Twitter: http://twitter.com/fh5co\n");
      out.write("	URL: http://FreeHTML5.co\n");
      out.write("-->\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("	<title>BIOMaaS </title>\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("	<meta name=\"description\" content=\"\" />\n");
      out.write("	<meta name=\"keywords\" content=\"free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive\" />\n");
      out.write("	<meta name=\"author\" content=\"FreeHTML5.co\" />\n");
      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("  	<!-- Facebook and Twitter integration -->\n");
      out.write("	<meta property=\"og:title\" content=\"\"/>\n");
      out.write("	<meta property=\"og:image\" content=\"\"/>\n");
      out.write("	<meta property=\"og:url\" content=\"\"/>\n");
      out.write("	<meta property=\"og:site_name\" content=\"\"/>\n");
      out.write("	<meta property=\"og:description\" content=\"\"/>\n");
      out.write("	<meta name=\"twitter:title\" content=\"\" />\n");
      out.write("	<meta name=\"twitter:image\" content=\"\" />\n");
      out.write("	<meta name=\"twitter:url\" content=\"\" />\n");
      out.write("	<meta name=\"twitter:card\" content=\"\" />\n");
      out.write("\n");
      out.write("	<link href='https://fonts.googleapis.com/css?family=Raleway:400,300,600,400italic,700' rel='stylesheet' type='text/css'>\n");
      out.write("	\n");
      out.write("	<!-- Animate.css -->\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/animate.css\">\n");
      out.write("	<!-- Icomoon Icon Fonts-->\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/icomoon.css\">\n");
      out.write("	<!-- Bootstrap  -->\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("\n");
      out.write("	<!-- Magnific Popup -->\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("	<!-- Owl Carousel  -->\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\n");
      out.write("\n");
      out.write("	<!-- Theme style  -->\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\n");
      out.write("	<!-- Modernizr JS -->\n");
      out.write("	<script src=\"js/modernizr-2.6.2.min.js\"></script>\n");
      out.write("	<!-- FOR IE9 below -->\n");
      out.write("	<!--[if lt IE 9]>\n");
      out.write("	<script src=\"js/respond.min.js\"></script>\n");
      out.write("	<![endif]-->\n");
      out.write("\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		\n");
      out.write("	<div class=\"gtco-loader\"></div>\n");
      out.write("	\n");
      out.write("	<div id=\"page\">\n");
      out.write("	<nav class=\"gtco-nav\" role=\"navigation\">\n");
      out.write("		<div class=\"gtco-container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-xs-2\">\n");
      out.write("					<div id=\"gtco-logo\"><a href=\"index.html\">BIOMaaS.</a></div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-xs-10 text-right menu-1\">\n");
      out.write("					<ul>\n");
      out.write("						<li><a href=\"index.html\">Home</a></li>\n");
      out.write("						<li class=\"active\"><a href=\"about.html\">About</a></li>\n");
      out.write("						<li class=\"has-dropdown\">\n");
      out.write("							<a href=\"services.html\">Services</a>\n");
      out.write("							<ul class=\"dropdown\">\n");
      out.write("								<li><a href=\"#\">ID</a></li>\n");
      out.write("								<li><a href=\"#\">Files</a></li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("						<!--<li class=\"has-dropdown\">\n");
      out.write("							<a href=\"#\">Dropdown</a>\n");
      out.write("							<ul class=\"dropdown\">\n");
      out.write("								<li><a href=\"#\">HTML5</a></li>\n");
      out.write("								<li><a href=\"#\">CSS3</a></li>\n");
      out.write("								<li><a href=\"#\">Sass</a></li>\n");
      out.write("								<li><a href=\"#\">jQuery</a></li>\n");
      out.write("							</ul>\n");
      out.write("						</li>-->\n");
      out.write("						<li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("\n");
      out.write("	<header id=\"gtco-header\" class=\"gtco-cover gtco-cover-sm\" role=\"banner\" style=\"background-image:url(images/img_bg_1.jpg);\">\n");
      out.write("		<div class=\"overlay\"></div>\n");
      out.write("		<div class=\"gtco-container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-md-8 col-md-offset-2 text-center\">\n");
      out.write("					<div class=\"display-t\">\n");
      out.write("						<div class=\"display-tc animate-box\" data-animate-effect=\"fadeIn\">\n");
      out.write("							<h1>About Us</h1>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	<footer id=\"gtco-footer\" role=\"contentinfo\">\n");
      out.write("		<div class=\"gtco-container\">\n");
      out.write("			<div class=\"row row-pb-md\">\n");
      out.write("				<div class=\"col-md-2 col-sm-4 col-xs-6 \">\n");
      out.write("					<ul class=\"gtco-footer-links\">\n");
      out.write("						<li><a href=\"#\">About</a></li>\n");
      out.write("						<li><a href=\"#\">Help</a></li>\n");
      out.write("						<li><a href=\"#\">Contact</a></li>\n");
      out.write("						<li><a href=\"#\">Terms</a></li>\n");
      out.write("						<li><a href=\"#\">Meetups</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-2 col-sm-4 col-xs-6\">\n");
      out.write("					<ul class=\"gtco-footer-links\">\n");
      out.write("						<li><a href=\"#\">Creative Design</a></li>\n");
      out.write("						<li><a href=\"#\">Branding</a></li>\n");
      out.write("						<li><a href=\"#\">Illustration</a></li>\n");
      out.write("						<li><a href=\"#\">Subscribe</a></li>\n");
      out.write("						<li><a href=\"#\">Monthly Event</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"clearfix visible-xs-block\"></div>\n");
      out.write("\n");
      out.write("				<div class=\"col-md-2 col-sm-4 col-xs-6\">\n");
      out.write("					<ul class=\"gtco-footer-links\">\n");
      out.write("						<li><a href=\"#\">About</a></li>\n");
      out.write("						<li><a href=\"#\">Help</a></li>\n");
      out.write("						<li><a href=\"#\">Contact</a></li>\n");
      out.write("						<li><a href=\"#\">Terms</a></li>\n");
      out.write("						<li><a href=\"#\">Meetups</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"clearfix visible-sm-block\"></div>\n");
      out.write("\n");
      out.write("				<div class=\"col-md-2 col-sm-4 col-xs-6\">\n");
      out.write("					<ul class=\"gtco-footer-links\">\n");
      out.write("						<li><a href=\"#\">Shop</a></li>\n");
      out.write("						<li><a href=\"#\">Privacy</a></li>\n");
      out.write("						<li><a href=\"#\">Testimonials</a></li>\n");
      out.write("						<li><a href=\"#\">Handbook</a></li>\n");
      out.write("						<li><a href=\"#\">Held Desk</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"clearfix visible-xs-block\"></div>\n");
      out.write("\n");
      out.write("				<div class=\"col-md-2 col-sm-4 col-xs-6\">\n");
      out.write("					<ul class=\"gtco-footer-links\">\n");
      out.write("						<li><a href=\"#\">Find Designers</a></li>\n");
      out.write("						<li><a href=\"#\">Find Deelopers</a></li>\n");
      out.write("						<li><a href=\"#\">Teams</a></li>\n");
      out.write("						<li><a href=\"#\">Advertise</a></li>\n");
      out.write("						<li><a href=\"#\">API</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"col-md-2 col-sm-4 col-xs-6\">\n");
      out.write("					<ul class=\"gtco-footer-links\">\n");
      out.write("						<li><a href=\"#\">About</a></li>\n");
      out.write("						<li><a href=\"#\">Help</a></li>\n");
      out.write("						<li><a href=\"#\">Contact</a></li>\n");
      out.write("						<li><a href=\"#\">Terms</a></li>\n");
      out.write("						<li><a href=\"#\">Meetups</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"row copyright\">\n");
      out.write("				<div class=\"col-md-12\">\n");
      out.write("					<p class=\"pull-left\">\n");
      out.write("						<small class=\"block\">&copy; 2016 Free HTML5. All Rights Reserved.</small> \n");
      out.write("						<small class=\"block\">Designed by <a href=\"http://freehtml5.co/\" target=\"_blank\">FreeHTML5.co</a> Demo Images: <a href=\"http://unsplash.co/\" target=\"_blank\">Unsplash</a></small>\n");
      out.write("					</p>\n");
      out.write("					<p class=\"pull-right\">\n");
      out.write("						<ul class=\"gtco-social-icons pull-right\">\n");
      out.write("							<li><a href=\"#\"><i class=\"icon-twitter\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"icon-facebook\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"icon-linkedin\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"icon-dribbble\"></i></a></li>\n");
      out.write("						</ul>\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"gototop js-top\">\n");
      out.write("		<a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up\"></i></a>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<!-- jQuery -->\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\n");
      out.write("	<!-- jQuery Easing -->\n");
      out.write("	<script src=\"js/jquery.easing.1.3.js\"></script>\n");
      out.write("	<!-- Bootstrap -->\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("	<!-- Waypoints -->\n");
      out.write("	<script src=\"js/jquery.waypoints.min.js\"></script>\n");
      out.write("	<!-- Carousel -->\n");
      out.write("	<script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("	<!-- countTo -->\n");
      out.write("	<script src=\"js/jquery.countTo.js\"></script>\n");
      out.write("	<!-- Magnific Popup -->\n");
      out.write("	<script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("	<script src=\"js/magnific-popup-options.js\"></script>\n");
      out.write("	<!-- Main -->\n");
      out.write("	<script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
